apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mangosd-pvc-etc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: mangosd-nfs-etc
status: {}
