apiVersion: v1
kind: PersistentVolume
metadata:
  name: mangosd-pv-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mangosd-nfs-data
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.124.11
    path: /wow/extracted-data
