apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-database
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.124.11
    path: /wow/data/database