apiVersion: v1
kind: Service
metadata:
  name: mangosd
  labels:
    {{- include "realmd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceMangosd.type }}
  loadBalancerIP: {{ .Values.serviceMangosd.loadBalancerIP }}
  ports:
    - port: {{ .Values.serviceMangosd.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "realmd.selectorLabels" . | nindent 4 }}
