---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mangosd-nfs-etc
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.124.11
  share: /wow/data/mangosd_etc
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
