apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mangosd-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: mangosd-nfs-data
status: {}
